[package]
name = "eigheses"
version = "0.1.0"
edition = "2021"
license = "ISC"
description = "Rust implementation of libass for rendering and processing ASS subtitle file"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
